// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7jErrP22dhr8U1kS2XRgSNrmdXBdKcKw',
    appId: '1:7311521816:web:8d3353a466fa5b4a392b6d',
    messagingSenderId: '7311521816',
    projectId: 'online-booking-b241b',
    authDomain: 'online-booking-b241b.firebaseapp.com',
    storageBucket: 'online-booking-b241b.appspot.com',
    measurementId: 'G-CV30RNQGJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCCewrSKU1heeZpysd-xo7EDd-45L9aNg',
    appId: '1:7311521816:android:737f6bab3d7bd9b3392b6d',
    messagingSenderId: '7311521816',
    projectId: 'online-booking-b241b',
    storageBucket: 'online-booking-b241b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkEkVGYQ4pnj_04s9fBmkwrqCAY3oVCXU',
    appId: '1:7311521816:ios:fac4aadb38ac2169392b6d',
    messagingSenderId: '7311521816',
    projectId: 'online-booking-b241b',
    storageBucket: 'online-booking-b241b.appspot.com',
    iosBundleId: 'com.example.userside',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkEkVGYQ4pnj_04s9fBmkwrqCAY3oVCXU',
    appId: '1:7311521816:ios:fac4aadb38ac2169392b6d',
    messagingSenderId: '7311521816',
    projectId: 'online-booking-b241b',
    storageBucket: 'online-booking-b241b.appspot.com',
    iosBundleId: 'com.example.userside',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7jErrP22dhr8U1kS2XRgSNrmdXBdKcKw',
    appId: '1:7311521816:web:da76d2c3b5c244c2392b6d',
    messagingSenderId: '7311521816',
    projectId: 'online-booking-b241b',
    authDomain: 'online-booking-b241b.firebaseapp.com',
    storageBucket: 'online-booking-b241b.appspot.com',
    measurementId: 'G-YB8M7L6E5L',
  );
}
